### PR TITLE
Added infinite scroll functionality

### PR DESCRIPTION
**Pull request by acondiff**
Works in two contexts, scrolling within the body, and scrolling within container element.
See in in action on codepen: http://codepen.io/acondiff/pen/yepggM

### CODE REVIEW

**Comment by s-yadav** [comment]
Hi  Austin,

I have a little concern with the following line
```js
if (infScrContScrollTop + 1500 >= infScrContInnerHeight - infScrContHeight) {		
                                infScrCont.removeEventListener('scroll', scrollCallback);		
                                var infiniteScrollPromise = scope.infiniteScroll();		
                                infiniteScrollPromise.then(function(data) {		
                                    infScrCont.addEventListener('scroll', scrollCallback);		
                                });		
                            }
```

1. Why +1500? I don't think hard coding that value is a good idea.
2. You are expecting infiniteScroll method returns a promise object "var infiniteScrollPromise = scope.infiniteScroll();", which sometime will not be the case. Sometimes it can be a synchronous call or async which does not return a promise object. We should not make that assumption. 
In fact, I think that's not required only. It should be developer choice to return from the function if a call is going on, like in codepen example.
```js
  vm.loadMoreShots = function() {
    if(vm.loadingMore) return;
    ......
}
```

Plus do we really need to make this as part of angulargrid? angular grid work very well with ng-infinite-scroll (https://sroze.github.io/ngInfiniteScroll/) module. See I have updated your codepen with infinite-scroll module and angular grid. http://codepen.io/s-yadav/pen/EPoOZo

ng-infinite-scroll is a well-maintained repository for infinite scroll problem, so I think we can use that instead of adding it on angulargrid. Though it makes sense to add on docs and add a demo to how to use angulargrid in conjunction to infinite-scroll.

**Comment by acondiff** [comment]
Regarding the 1500, I realized that right after I submitted the PR. I would have made that an attribute definable by the developer as a separate attribute. If not defined, it would default to 1500. This was something I just put together yesterday so if needed I would be happy to revise it. In my use case I need the infinite scroll to happen in a container. Does ngInfiniteScroll have the ability to bind the scroll event to a scrollable div rather than the document itself?

Also, I had plans to add virtual scrolling on top of this. I think that it would be appropriate to have infinite scroll in angulargrid considering that because they would work together. Plus if I were using separate modules to do this I would now have two or even three scroll events attached to one single object which would cause performance concerns.

In my project I am loading in thousands of items, and the browser gets massively sluggish when that amount of nodes are on the DOM and watchers are on the scope at once.

What are your thoughts on this?

**Comment by acondiff** [comment]
Also, when items are added after subsequent requests, items in previous batches sometimes shift around a bit even though those items have not changed in dimension. Would you have any idea on why that happens? Could it be that it didn't properly calculate the position to begin with due to some kind of a race condition?

**Comment by acondiff** [comment]
Regarding the promise, I think that if implemented, it should expect a promise. If the $http method is not used, the user could easily use $q to create one. I don't think there is anything wrong with requiring one if documented. Especially considering we need to know when to start listening for scroll events again. I suppose if we had to we could listen for a change in container height, then start listening again.

**Comment by s-yadav** [comment]
" Does ngInfiniteScroll have the ability to bind the scroll event to a scrollable div rather than the document itself? "

Yes, the codepen example I shared, I have assigned to a container instead of body.

Regarding promise object ,
I understand you are unbinding scroll event so it does not call same function twice. And you are waiting for promise object to be resolved to rebind scroll event.
There are many use cases to handle
- What if there is no more items to show, 
- What if conditionally I don't want to load any  more data
- What if any error caused during making an ajax request. 
- What if the result I am getting is not tall enough to cover a window height.
- What if I am getting data from js array synchronously instead of making a api call.

This are the concerns which I feel shouldn't be handled on the plugin itself. In the pen example I shared, you can just check if content is loading, and then return from the function. You can have any condition to return from the function. 

Plus I still feel ngInfiniteScroll is better to use in cojuction to angulargrid, as they have solved many trival use cases and well documented for infinte scroll specific cases. They also have scroll throttling option for performance. 
Regarding having two scroll events on same element, I don't feel that will lead to performance issue.

**Comment by s-yadav** [comment]
Removing / adding dom element depending on visible element at a particular moment of time. Is a different problem altogether. Which can be done without caring what we have to achieve infinite scroll. 
I will also rename the issue headline, as its confusing to what we were discussing on that issue.

**Pull request closed without merging**
